### ISSUE TITLE
customView is tableView

### ISSUE THREAD

**Issue by MysteryRan** [younatics/YNDropDownMenu#10]
i want to layout a tableView in YNDropDownView, it's unsupported?

**Comment by younatics** [comment]
Hello, @MysteryRan,
  I can't understand what you mean. Do you want a layout in my example project?

**Comment by MysteryRan** [comment]
sorry,  set tableView delegate in awakeFromNib

**Comment by younatics** [comment]
Great. I will close this issue :)
