### ISSUE TITLE
change height

### ISSUE THREAD

**Issue by MysteryRan** [younatics/YNDropDownMenu#11]
how can i change the views height, when i drawed views in xib, i override frame, this will  cause constraints conflict

**Comment by MysteryRan** [comment]
`class STSiftView: YNDropDownView {
    override var frame: CGRect {
        didSet {
            var newFrame = frame
            newFrame.size.height = 225
            newFrame.size.width = screenWidth
            super.frame = newFrame
        }
    }

}`

**Comment by younatics** [comment]
Hello @MysteryRan,
Do you need to change view height when view is opened?
If not, use `open func changeView(view: UIView, at index: Int)` method

**Comment by younatics** [comment]
Please reopen this issue if it is not

**Comment by MysteryRan** [comment]
`        let locationView = dropDownViews?[0] as! STLocationView
        locationView.frame = CGRect(x: 0, y: 0, width: screenWidth, height: 170)`  change like this, it's the best method
