### ISSUE TITLE
Support xib & sb

### ISSUE THREAD

**Issue by codwam** [younatics/YNDropDownMenu#13]

**Comment by younatics** [comment]
Hello @codwam ,
Currently, I support xib in drop down views. 
Could you tell me more about this issue?

**Comment by codwam** [comment]
Not the drop down views but the 

> YNDropDownMenu

Drag a view into xib and class change it to  

> YNDropDownMenu

It will be crash cause initWithCoder not implement

**Comment by younatics** [comment]
Hello @codwam  
I mad it not to call `fatal error` in coder method. [v2.3.2] (https://github.com/younatics/YNDropDownMenu/releases/tag/2.3.2)

please override and customize it. 
Thanks,
