### ISSUE TITLE
how can I change the top menu backgroundColor?

### ISSUE THREAD

**Issue by Pr-Chen** [younatics/YNDropDownMenu#17]
I need change the top menu backgroundColor to clear, you said use YNDropDownButton in [issue15](https://github.com/younatics/YNDropDownMenu/issues/15), but YNDropDownButton is not public, I can't use it by Carthage.
I need this:
![](https://ws1.sinaimg.cn/large/006tNc79ly1fhzkummpbzj30af0ijac4.jpg)

**Comment by ushehri** [comment]
I was able to change background color by editing the init() in YNDropDownMenuButton like this 

http://imgur.com/a/6nEnw

but honestly this is not a good way to do that , I mean why can't we change it using the build  in function.... 

hope this help for now.

Good luck
ushehri

**Comment by younatics** [comment]
I proceed some work right now. please wait just for a second

**Comment by younatics** [comment]
I added a function to change background color! see 2.3.3
