### ISSUE TITLE
Not Able to change backgroundColor nor Text color Both Always white ?? 

### ISSUE THREAD

**Issue by ushehri** [younatics/YNDropDownMenu#19]
Hi , 
I can not change background color nor the text color no matter what I do the always become white color..

IOS 10.3

http://imgur.com/a/2nnyo

**Comment by younatics** [comment]
I added a function to change background color! see 2.3.3

**Comment by ushehri** [comment]
Text color Is not Visiable ? Is there an issue in your demo implementation ? Because i follow 100% the example you provided
