### ISSUE TITLE
Error in Swift4-IOS11-Xcode9

### ISSUE THREAD

**Issue by siyavash4812** [younatics/YNDropDownMenu#21]
I have installed the most recent version of YNDropDownMenu however i got this error 
"/Users/x/Documents/IOS development/Kallos/Pods/YNDropDownMenu/YNDropDownMenu/YNDropDownMenu.swift:583:43: 'init(colorLiteralRed:green:blue:alpha:)' is unavailable: This initializer is only meant to be used by color literals"
<img width="1098" alt="screen shot 2017-10-02 at 12 10 14" src="https://user-images.githubusercontent.com/22658677/31074890-ad747e28-a76a-11e7-9f28-0b0beb32fc1c.png">

**Comment by siyavash4812** [comment]
Problem can be solved by changing colorLiteralRed to red. 
Please include this in your next update

**Comment by younatics** [comment]
I will update this library ASAP. Thanks!

**Comment by younatics** [comment]
Check latest version 3.0.0 thanks!
