### ISSUE TITLE
not set the view's frame x value = 0

### ISSUE THREAD

**Issue by zarvin** [younatics/YNDropDownMenu#4]
![1](https://cloud.githubusercontent.com/assets/8108745/23493548/96d8e396-ff47-11e6-9467-bb8438f8d570.gif)
change to:
`self.frame = CGRect(x: self.frame.origin.x, y: self.frame.origin.y, width: self.frame.width, height: CGFloat(self.menuHeight))`
![2](https://cloud.githubusercontent.com/assets/8108745/23493571/c7a4b02c-ff47-11e6-96a1-74e971c38929.gif)

**Comment by younatics** [comment]
Got it. It will be changed soon.

**Comment by younatics** [comment]
fixed at [v2.0.1](https://github.com/younatics/YNDropDownMenu/releases/tag/2.0.1)
