### ISSUE TITLE
Not working in my project

### ISSUE THREAD

**Issue by amitgajjar510** [younatics/YNDropDownMenu#9]
It is showing "Unable to find a specification for `YNDropDownMenu`" while installing pod.
My project's deployment target is 9.0.
What is the issue?

**Comment by younatics** [comment]
Hello @amitgajjar510, 
Did you try `pod install`?

**Comment by amitgajjar510** [comment]
Yes I tried

**Comment by younatics** [comment]
That's weird. I will check that situation right now.
Please try http://stackoverflow.com/questions/25913733/unable-to-find-a-specification-in-cocoapods

**Comment by amitgajjar510** [comment]
Have you checked?

**Comment by younatics** [comment]
Please try my answer above :)

**Comment by younatics** [comment]
Maybe, this is not my problem :( Please reopen this issue again if you don't solve it!

**Comment by younatics** [comment]
You can try `pod setup`. It will solve your problem :) 
If it is not worked, please reopen this issue.
